### ISSUE TITLE
buthow?

### ISSUE THREAD

**Issue by crmabs** [otti/FroniusModbusRtu#1]
Hi,
First, many thanks for sharing this repo. 
Where the heck did you find this information?

I'm looking for the same kind of thing for their newer smart meter TS100a. Reset or state register is what I'm after. I don't dare to spam the registers with write commands just to figure out which ones are the writable ones.
In my dreams I also see a complete list with descriptions, and such.
Andras

**Comment by otti** [comment]
Hi Andreas,

sorry for my realy late response :-)
>Where the heck did you find this information?

Sorry that I have to disappoint you. I did not "find" this information. I reverse engineered it. ;-)
I have just recorded the data between my inverter and the meter with a RS485 to USB converter. At the same time I had a look onto the values delivered by the inverter. (http://<inverter_ip>/solar_api/v1/GetPowerFlowRealtimeData.fcgi)

Then I tried to to find out which ModBus register fits best to the values from the website.

Regards,
Otti
