### ISSUE TITLE
Register 262..263, 268..269, 270..271 	

### ISSUE THREAD

**Issue by Matthias-C** [otti/FroniusModbusRtu#2]
Hi, I did some testing on a TS-65a Meter

My setup was 
A Meter and conditions readout via ESP Home,
Then I tried different loads to figure out the missing registers,

My loads 
- 60W Light bulb (Resistive Load)
- 600W VacumCleaner (Inductive Load)

With the test, I Figured out that
I'm pretty certain that this is  262..263 is PowerReal_P_Sum - 0.1W.

About 90% certain that 268..269 - Power Factor Sum -   0.001deg 

And this 270..271 read always zero. So I have no Clue, maybe - Current_AC_Sum -

**Comment by otti** [comment]
I have updated the register description.
Thanks
